# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e89f8612d887e1f3004ad523b1cbdad5a1edd03af17f72c0d531d97b010b479420e29c72be86c2b91860a4aed45059becd8da8efb34cf55627e6d19bb5ef87ef

test:
  secret_key_base: b146d6b555e60217d5b736817df6c65c2f2a84e5f1b0cf04a7bfb42637e458f32930175e8b76913dc834677a15a06b17d9aee997ede42e36ef3590f823cc037e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
